# Generated by Django 3.2.15 on 2022-08-17 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorited',
            field=models.ManyToManyField(blank=True, null=True, related_name='favored_user', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='recipes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, null=True, related_name='cart_user', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, null=True, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
